-- =========================================================
-- ABC CLASSIFICATION
-- Ranks products by total revenue and assigns each an ABC class:
--   A = top 80% of cumulative revenue (highest value products)
--   B = next 15% of cumulative revenue (mid value products)
--   C = bottom 5% of cumulative revenue (lowest value products)
--
-- Parameters:
--   $1: start_date (TIMESTAMP or NULL) — filters orders on or after this date
--       NULL means no date filter is applied.
--
-- Returns one row per product with its ABC class and cumulative
-- revenue percentage.
-- =========================================================

WITH product_revenue AS (
    -- Step 1: Calculate total revenue and items sold per product
    SELECT
        p.product_id,
        p.product_category_name,

        -- Total number of times this product was sold
        COUNT(oi.order_id)      AS total_items_sold,

        -- Total revenue generated by this product
        SUM(oi.price)           AS total_revenue

    FROM order_items oi

    JOIN products p
        ON oi.product_id = p.product_id

    JOIN orders o
        ON oi.order_id = o.order_id

    -- $1: optional start date filter — NULL means no date filter applied
    WHERE ($1 IS NULL OR o.order_purchase_timestamp >= $1::TIMESTAMP)

    GROUP BY
        p.product_id,
        p.product_category_name
),

ranked AS (
    -- Step 2: Calculate cumulative revenue percentage across all products
    -- sorted from highest to lowest revenue
    SELECT
        product_id,
        product_category_name,
        total_items_sold,
        total_revenue,

        -- Cumulative share of total revenue up to and including this product
        SUM(total_revenue) OVER (
            ORDER BY total_revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) / SUM(total_revenue) OVER () AS cumulative_revenue_pct

    FROM product_revenue
)

-- Step 3: Assign ABC class based on cumulative revenue percentage
SELECT
    product_id,
    product_category_name,
    total_items_sold,
    total_revenue,

    -- Round to 4 decimal places for readability
    ROUND(cumulative_revenue_pct, 4)    AS cumulative_revenue_pct,

    -- ABC classification thresholds:
    --   A: drives the first 80% of total revenue
    --   B: drives the next 15% (80-95%)
    --   C: drives the remaining 5% (95-100%)
    CASE
        WHEN cumulative_revenue_pct <= 0.80 THEN 'A'
        WHEN cumulative_revenue_pct <= 0.95 THEN 'B'
        ELSE 'C'
    END AS abc_class

FROM ranked

ORDER BY
    total_revenue DESC
