-- =========================================================
-- SELLER SCORECARD
-- Calculates per-seller performance metrics including total
-- items sold, revenue, and average review score.
-- Filterable by order start date ($1) and seller state ($2).
--
-- Parameters:
--   $1: start_date (TIMESTAMP or NULL) — filters orders on or after this date
--   $2: seller_state (VARCHAR or NULL) — filters sellers by state code (e.g. 'SP')
--
-- Returns one row per seller.
-- =========================================================

SELECT
    s.seller_id,
    s.seller_state,

    -- Total number of individual items sold by this seller
    COUNT(oi.order_id)                          AS total_items_sold,

    -- Total revenue generated by this seller across all orders
    SUM(oi.price)                               AS total_revenue,

    -- Average item price for this seller
    AVG(oi.price)                               AS avg_item_price,

    -- Number of unique orders this seller fulfilled
    COUNT(DISTINCT oi.order_id)                 AS total_orders,

    -- Average customer review score for this seller's orders
    AVG(r.review_score)                         AS avg_review_score

FROM sellers s

JOIN order_items oi
    ON s.seller_id = oi.seller_id

JOIN orders o
    ON oi.order_id = o.order_id

-- Left join reviews so sellers with no reviews are still included
LEFT JOIN order_reviews r
    ON oi.order_id = r.order_id

-- $1: optional start date filter — NULL means no date filter applied
-- $2: optional seller state filter — NULL means all states included
WHERE ($1 IS NULL OR o.order_purchase_timestamp >= $1::TIMESTAMP)
  AND ($2 IS NULL OR s.seller_state = $2)

GROUP BY
    s.seller_id,
    s.seller_state

ORDER BY
    total_revenue DESC
